### ISSUE TITLE
Batch size >1 causes error

### ISSUE THREAD

**Issue by poisenbery** [Fannovel16/comfy_controlnet_preprocessors#11]
Everything works well until batch size increased above 1, then error.

``` Traceback (most recent call last):
  File "V:\AI\ComfyUI\execution.py", line 174, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "V:\AI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "V:\AI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "V:\AI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  [Previous line repeated 2 more times]
  File "V:\AI\ComfyUI\execution.py", line 63, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "V:\AI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 104, in estimate_depth
    depth_map_np, normal_map_np = common_annotator_call(midas.MidasDetector(), image, a, bg_threshold)
  File "V:\AI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 16, in common_annotator_call
    call_result = annotator_callback(img_tensor_to_np(tensor_image), *args)
  File "V:\AI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\midas\__init__.py", line 14, in __call__
    assert input_image.ndim == 3
AssertionError ```

**Comment by Fannovel16** [comment]
Can you share your workflow.json?

**Comment by poisenbery** [comment]
My bad, I wasn't specific. It's actually when a batch size >1 is passed into the preprocessors. Different error with this setup:

``` Traceback (most recent call last):
  File "V:\AI\ComfyUI\execution.py", line 174, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "V:\AI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "V:\AI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "V:\AI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  [Previous line repeated 1 more time]
  File "V:\AI\ComfyUI\execution.py", line 63, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "V:\AI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 39, in detect_edge
    CATEGORY = "preprocessors/edge_line"
  File "V:\AI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 21, in common_annotator_call
    if type(annotator_callback) is openpose.OpenposeDetector:
  File "V:\AI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\util.py", line 44, in resize_image
    W = int(np.round(W / 64.0)) * 64
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4065: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize' ```
[workflow.json.txt](https://github.com/Fannovel16/comfy_controlnet_preprocessors/files/11069332/workflow.json.txt)

**Comment by poisenbery** [comment]
Workflow.json
It's not uploading for some reason

``` {
  "last_node_id": 18,
  "last_link_id": 26,
  "nodes": [
    {
      "id": 13,
      "type": "ControlNetLoader",
      "pos": [
        1593.5454545454545,
        879.3636363636361
      ],
      "size": {
        "0": 315,
        "1": 58
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "outputs": [
        {
          "name": "CONTROL_NET",
          "type": "CONTROL_NET",
          "links": [
            11
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        "ControlNet\\control_sd15_canny.pth"
      ]
    },
    {
      "id": 5,
      "type": "EmptyLatentImage",
      "pos": [
        473,
        609
      ],
      "size": {
        "0": 315,
        "1": 106
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            2
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        512,
        512,
        2
      ]
    },
    {
      "id": 10,
      "type": "CannyEdgePreprocesor",
      "pos": [
        1593,
        719
      ],
      "size": {
        "0": 315,
        "1": 106
      },
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "image",
          "type": "IMAGE",
          "link": 16
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            12
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        100,
        200,
        "disable"
      ]
    },
    {
      "id": 3,
      "type": "KSampler",
      "pos": [
        983,
        172
      ],
      "size": {
        "0": 315,
        "1": 262
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 1
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 15
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 6
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 2
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            7,
            20
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        827396696673578,
        true,
        20,
        8,
        "euler",
        "normal",
        1
      ]
    },
    {
      "id": 14,
      "type": "KSampler",
      "pos": [
        2099,
        164
      ],
      "size": {
        "0": 315,
        "1": 262
      },
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 24
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 22
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 23
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 20
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            17
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        51265399920022,
        true,
        20,
        8,
        "euler",
        "normal",
        0.6899999999999997
      ]
    },
    {
      "id": 6,
      "type": "CLIPTextEncode",
      "pos": [
        415,
        186
      ],
      "size": {
        "0": 422.84503173828125,
        "1": 164.31304931640625
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 3
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            15,
            21
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        "masterpiece best quality girl"
      ]
    },
    {
      "id": 12,
      "type": "ControlNetApply",
      "pos": [
        2040.545454545455,
        617.3636363636361
      ],
      "size": {
        "0": 317.4000244140625,
        "1": 98
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "conditioning",
          "type": "CONDITIONING",
          "link": 21
        },
        {
          "name": "control_net",
          "type": "CONTROL_NET",
          "link": 11
        },
        {
          "name": "image",
          "type": "IMAGE",
          "link": 12
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            22
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        1
      ]
    },
    {
      "id": 7,
      "type": "CLIPTextEncode",
      "pos": [
        413,
        389
      ],
      "size": {
        "0": 425.27801513671875,
        "1": 180.6060791015625
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 5
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            6,
            23
          ],
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        "bad hands"
      ]
    },
    {
      "id": 4,
      "type": "CheckpointLoaderSimple",
      "pos": [
        26,
        474
      ],
      "size": {
        "0": 315,
        "1": 98
      },
      "flags": {},
      "order": 2,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            1,
            24
          ],
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            3,
            5
          ],
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            8,
            18
          ],
          "slot_index": 2
        }
      ],
      "properties": {},
      "widgets_values": [
        "Stable-diffusion\\Orange Mixes\\OrangeMixs\\OM3\\abyssorangemix3AOM3_aom3.safetensors"
      ]
    },
    {
      "id": 17,
      "type": "PreviewImage",
      "pos": [
        1769.394668060303,
        79.97987377929695
      ],
      "size": {
        "0": 210,
        "1": 26
      },
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 25
        }
      ],
      "properties": {}
    },
    {
      "id": 8,
      "type": "VAEDecode",
      "pos": [
        1367,
        159
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 7
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 8
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            16,
            25
          ],
          "slot_index": 0
        }
      ],
      "properties": {}
    },
    {
      "id": 15,
      "type": "VAEDecode",
      "pos": [
        2549,
        133
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 17
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 18
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            26
          ],
          "slot_index": 0
        }
      ],
      "properties": {}
    },
    {
      "id": 18,
      "type": "PreviewImage",
      "pos": [
        2934,
        160
      ],
      "size": {
        "0": 210,
        "1": 26
      },
      "flags": {},
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 26
        }
      ],
      "properties": {}
    }
  ],
  "links": [
    [
      1,
      4,
      0,
      3,
      0,
      "MODEL"
    ],
    [
      2,
      5,
      0,
      3,
      3,
      "LATENT"
    ],
    [
      3,
      4,
      1,
      6,
      0,
      "CLIP"
    ],
    [
      5,
      4,
      1,
      7,
      0,
      "CLIP"
    ],
    [
      6,
      7,
      0,
      3,
      2,
      "CONDITIONING"
    ],
    [
      7,
      3,
      0,
      8,
      0,
      "LATENT"
    ],
    [
      8,
      4,
      2,
      8,
      1,
      "VAE"
    ],
    [
      11,
      13,
      0,
      12,
      1,
      "CONTROL_NET"
    ],
    [
      12,
      10,
      0,
      12,
      2,
      "IMAGE"
    ],
    [
      15,
      6,
      0,
      3,
      1,
      "CONDITIONING"
    ],
    [
      16,
      8,
      0,
      10,
      0,
      "IMAGE"
    ],
    [
      17,
      14,
      0,
      15,
      0,
      "LATENT"
    ],
    [
      18,
      4,
      2,
      15,
      1,
      "VAE"
    ],
    [
      20,
      3,
      0,
      14,
      3,
      "LATENT"
    ],
    [
      21,
      6,
      0,
      12,
      0,
      "CONDITIONING"
    ],
    [
      22,
      12,
      0,
      14,
      1,
      "CONDITIONING"
    ],
    [
      23,
      7,
      0,
      14,
      2,
      "CONDITIONING"
    ],
    [
      24,
      4,
      0,
      14,
      0,
      "MODEL"
    ],
    [
      25,
      8,
      0,
      17,
      0,
      "IMAGE"
    ],
    [
      26,
      15,
      0,
      18,
      0,
      "IMAGE"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {},
  "version": 0.4
}

```

**Comment by Fannovel16** [comment]
I understand the problem now. Your case is unusual because preprocessor nodes expect IMAGE input to be a Tensor with batch size 1 from a LoadImage node. But the IMAGE input in this case has batch size 2. Idk if ControlNetApply accept that input.

**Comment by Fannovel16** [comment]
Fixed: https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/ebc8b4d856490799d8d5d7bcc5e246f1fc690288
