### ISSUE TITLE
Impossible to install on a huggingface Docker container. Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### ISSUE THREAD

**Issue by cr4i50n** [Fannovel16/comfy_controlnet_preprocessors#12]
My ComfyUI docker is runnign ok but I cannot install this controlnet_preprocessor custom nodes repo.
The cuda environment allows ComfyUI to run. Not this install.py script though. 

`q5th5 2023-03-24T20:41:20.695Z No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
`
`...`
`...`
`...`
`
--> ERROR: process "/bin/sh -c cd $HOME/ComfyUI/custom_nodes/comfy_controlnet_preprocessors && python -u install.py" did not complete successfully: exit code: 1
`

Any suggestions?  Provided below is the CLI dump leading to the error in question

<details><summary>CLI Dump</summary>
<p>

q5th5 2023-03-24T20:41:01.330Z --> RUN cd /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors && python -u install.py
q5th5 2023-03-24T20:41:01.480Z Installing requirements...
q5th5 2023-03-24T20:41:04.485Z Defaulting to user installation because normal site-packages is not writeable
q5th5 2023-03-24T20:41:04.485Z Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
q5th5 2023-03-24T20:41:04.892Z Collecting opencv-contrib-python
q5th5 2023-03-24T20:41:04.892Z   Downloading opencv_contrib_python-4.7.0.72-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (67.9 MB)
q5th5 2023-03-24T20:41:05.594Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 MB 58.8 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:05.724Z Collecting opencv-python
q5th5 2023-03-24T20:41:05.875Z   Downloading opencv_python-4.7.0.72-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.8 MB)
q5th5 2023-03-24T20:41:06.265Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.8/61.8 MB 64.5 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:06.265Z Collecting timm==0.6.12
q5th5 2023-03-24T20:41:06.416Z   Downloading timm-0.6.12-py3-none-any.whl (549 kB)
q5th5 2023-03-24T20:41:06.416Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.1/549.1 kB 166.0 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:06.416Z Requirement already satisfied: torchvision in /home/user/.local/lib/python3.10/site-packages (from -r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (0.14.1+cu117)
q5th5 2023-03-24T20:41:06.416Z Requirement already satisfied: scipy in /home/user/.local/lib/python3.10/site-packages (from -r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 5)) (1.10.1)
q5th5 2023-03-24T20:41:06.520Z Collecting matplotlib
q5th5 2023-03-24T20:41:06.621Z   Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
q5th5 2023-03-24T20:41:06.762Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 135.2 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:06.762Z Collecting scikit-image
q5th5 2023-03-24T20:41:06.912Z   Downloading scikit_image-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.2 MB)
q5th5 2023-03-24T20:41:06.912Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 156.4 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:07.032Z Collecting prettytable==3.6.0
q5th5 2023-03-24T20:41:07.032Z   Downloading prettytable-3.6.0-py3-none-any.whl (27 kB)
q5th5 2023-03-24T20:41:07.032Z Collecting svglib
q5th5 2023-03-24T20:41:07.032Z   Downloading svglib-1.5.1.tar.gz (913 kB)
q5th5 2023-03-24T20:41:07.032Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 913.9/913.9 kB 201.8 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:07.032Z   Preparing metadata (setup.py): started
q5th5 2023-03-24T20:41:07.333Z   Preparing metadata (setup.py): finished with status 'done'
q5th5 2023-03-24T20:41:07.613Z Collecting reportlab
q5th5 2023-03-24T20:41:07.613Z   Downloading reportlab-3.6.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
q5th5 2023-03-24T20:41:07.613Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 207.0 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:07.613Z Collecting addict
q5th5 2023-03-24T20:41:07.613Z   Downloading addict-2.4.0-py3-none-any.whl (3.8 kB)
q5th5 2023-03-24T20:41:07.613Z Collecting yapf
q5th5 2023-03-24T20:41:07.745Z   Downloading yapf-0.32.0-py2.py3-none-any.whl (190 kB)
q5th5 2023-03-24T20:41:07.745Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.2/190.2 kB 124.1 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: torch>=1.7 in /home/user/.local/lib/python3.10/site-packages (from timm==0.6.12->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 3)) (1.13.1+cu117)
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: pyyaml in /home/user/.local/lib/python3.10/site-packages (from timm==0.6.12->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 3)) (6.0)
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: huggingface-hub in /home/user/.local/lib/python3.10/site-packages (from timm==0.6.12->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 3)) (0.13.3)
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: wcwidth in /home/user/.local/lib/python3.10/site-packages (from prettytable==3.6.0->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 8)) (0.2.6)
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: numpy>=1.21.2 in /home/user/.local/lib/python3.10/site-packages (from opencv-contrib-python->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 1)) (1.24.2)
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: requests in /home/user/.local/lib/python3.10/site-packages (from torchvision->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (2.28.2)
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: typing-extensions in /home/user/.local/lib/python3.10/site-packages (from torchvision->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (4.5.0)
q5th5 2023-03-24T20:41:07.745Z Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/user/.local/lib/python3.10/site-packages (from torchvision->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (9.4.0)
q5th5 2023-03-24T20:41:07.745Z Collecting cycler>=0.10
q5th5 2023-03-24T20:41:07.895Z   Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
q5th5 2023-03-24T20:41:07.895Z Collecting python-dateutil>=2.7
q5th5 2023-03-24T20:41:07.895Z   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
q5th5 2023-03-24T20:41:07.895Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 95.7 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.016Z Collecting fonttools>=4.22.0
q5th5 2023-03-24T20:41:08.016Z   Downloading fonttools-4.39.2-py3-none-any.whl (1.0 MB)
q5th5 2023-03-24T20:41:08.016Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 172.9 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.016Z Collecting pyparsing>=2.3.1
q5th5 2023-03-24T20:41:08.140Z   Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
q5th5 2023-03-24T20:41:08.140Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 74.4 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.140Z Requirement already satisfied: packaging>=20.0 in /home/user/.local/lib/python3.10/site-packages (from matplotlib->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 6)) (23.0)
q5th5 2023-03-24T20:41:08.140Z Collecting contourpy>=1.0.1
q5th5 2023-03-24T20:41:08.245Z   Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
q5th5 2023-03-24T20:41:08.245Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 148.1 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.245Z Collecting kiwisolver>=1.0.1
q5th5 2023-03-24T20:41:08.396Z   Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
q5th5 2023-03-24T20:41:08.396Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 232.7 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.528Z Collecting PyWavelets>=1.1.1
q5th5 2023-03-24T20:41:08.528Z   Downloading PyWavelets-1.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.8 MB)
q5th5 2023-03-24T20:41:08.528Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 153.3 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.528Z Collecting lazy_loader>=0.1
q5th5 2023-03-24T20:41:08.670Z   Downloading lazy_loader-0.2-py3-none-any.whl (8.6 kB)
q5th5 2023-03-24T20:41:08.670Z Collecting networkx>=2.8
q5th5 2023-03-24T20:41:08.670Z   Downloading https://download.pytorch.org/whl/networkx-3.0-py3-none-any.whl (2.0 MB)
q5th5 2023-03-24T20:41:08.670Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 212.2 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.670Z Collecting imageio>=2.4.1
q5th5 2023-03-24T20:41:08.771Z   Downloading imageio-2.26.1-py3-none-any.whl (3.4 MB)
q5th5 2023-03-24T20:41:08.771Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 256.7 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.771Z Collecting tifffile>=2019.7.26
q5th5 2023-03-24T20:41:08.922Z   Downloading tifffile-2023.3.21-py3-none-any.whl (218 kB)
q5th5 2023-03-24T20:41:08.922Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 218.7/218.7 kB 96.4 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:08.922Z Collecting cssselect2>=0.2.0
q5th5 2023-03-24T20:41:08.922Z   Downloading cssselect2-0.7.0-py3-none-any.whl (15 kB)
q5th5 2023-03-24T20:41:09.173Z Collecting lxml
q5th5 2023-03-24T20:41:09.173Z   Downloading lxml-4.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
q5th5 2023-03-24T20:41:09.299Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 174.3 MB/s eta 0:00:00
q5th5 2023-03-24T20:41:09.299Z Collecting tinycss2>=0.6.0
q5th5 2023-03-24T20:41:09.299Z   Downloading tinycss2-1.2.1-py3-none-any.whl (21 kB)
q5th5 2023-03-24T20:41:09.299Z Collecting webencodings
q5th5 2023-03-24T20:41:09.449Z   Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
q5th5 2023-03-24T20:41:09.556Z Collecting six>=1.5
q5th5 2023-03-24T20:41:09.556Z   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
q5th5 2023-03-24T20:41:09.556Z Requirement already satisfied: filelock in /home/user/.local/lib/python3.10/site-packages (from huggingface-hub->timm==0.6.12->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 3)) (3.10.4)
q5th5 2023-03-24T20:41:09.707Z Requirement already satisfied: tqdm>=4.42.1 in /home/user/.local/lib/python3.10/site-packages (from huggingface-hub->timm==0.6.12->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 3)) (4.65.0)
q5th5 2023-03-24T20:41:09.707Z Requirement already satisfied: certifi>=2017.4.17 in /home/user/.local/lib/python3.10/site-packages (from requests->torchvision->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (2022.12.7)
q5th5 2023-03-24T20:41:09.707Z Requirement already satisfied: idna<4,>=2.5 in /home/user/.local/lib/python3.10/site-packages (from requests->torchvision->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (3.4)
q5th5 2023-03-24T20:41:09.707Z Requirement already satisfied: charset-normalizer<4,>=2 in /home/user/.local/lib/python3.10/site-packages (from requests->torchvision->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (3.1.0)
q5th5 2023-03-24T20:41:09.707Z Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/user/.local/lib/python3.10/site-packages (from requests->torchvision->-r /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/requirements.txt (line 4)) (1.26.15)
q5th5 2023-03-24T20:41:09.707Z Building wheels for collected packages: svglib
q5th5 2023-03-24T20:41:09.707Z   Building wheel for svglib (setup.py): started
q5th5 2023-03-24T20:41:09.824Z   Building wheel for svglib (setup.py): finished with status 'done'
q5th5 2023-03-24T20:41:09.974Z   Created wheel for svglib: filename=svglib-1.5.1-py3-none-any.whl size=30920 sha256=8b3d5def56a30203c301b5b4fd5fd63d8373fa6627bff8c42d075b537d745ea0
q5th5 2023-03-24T20:41:09.974Z   Stored in directory: /home/user/.cache/pip/wheels/56/9f/90/f37f4b9dbf82987a24ae14f15586e96715cb669a4710b3b85d
q5th5 2023-03-24T20:41:09.974Z Successfully built svglib
q5th5 2023-03-24T20:41:10.725Z Installing collected packages: yapf, webencodings, addict, tinycss2, tifffile, six, reportlab, PyWavelets, pyparsing, prettytable, opencv-python, opencv-contrib-python, networkx, lxml, lazy_loader, kiwisolver, imageio, fonttools, cycler, contourpy, scikit-image, python-dateutil, cssselect2, timm, svglib, matplotlib
q5th5 2023-03-24T20:41:15.834Z   Attempting uninstall: timm
q5th5 2023-03-24T20:41:15.834Z     Found existing installation: timm 0.6.13
q5th5 2023-03-24T20:41:15.834Z     Uninstalling timm-0.6.13:
q5th5 2023-03-24T20:41:15.985Z       Successfully uninstalled timm-0.6.13
q5th5 2023-03-24T20:41:17.321Z Successfully installed PyWavelets-1.4.1 addict-2.4.0 contourpy-1.0.7 cssselect2-0.7.0 cycler-0.11.0 fonttools-4.39.2 imageio-2.26.1 kiwisolver-1.4.4 lazy_loader-0.2 lxml-4.9.2 matplotlib-3.7.1 networkx-3.0 opencv-contrib-python-4.7.0.72 opencv-python-4.7.0.72 prettytable-3.6.0 pyparsing-3.0.9 python-dateutil-2.8.2 reportlab-3.6.12 scikit-image-0.20.0 six-1.16.0 svglib-1.5.1 tifffile-2023.3.21 timm-0.6.12 tinycss2-1.2.1 webencodings-0.5.1 yapf-0.32.0
q5th5 2023-03-24T20:41:20.695Z No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
q5th5 2023-03-24T20:41:25.504Z Download models...
q5th5 2023-03-24T20:41:27.442Z Downloading: "https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator/ckpts/network-bsds500.pth" to /home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/ckpts/network-bsds500.pth
q5th5 2023-03-24T20:41:27.442Z 
q5th5 2023-03-24T20:41:28.601Z 
  0%|          | 0.00/56.1M [00:00<?, ?B/s]
 33%|███▎      | 18.3M/56.1M [00:00<00:00, 192MB/s]
 65%|██████▌   | 36.6M/56.1M [00:00<00:00, 68.4MB/s]
 89%|████████▉ | 49.9M/56.1M [00:00<00:00, 81.2MB/s]
100%|██████████| 56.1M/56.1M [00:00<00:00, 72.5MB/s]
q5th5 2023-03-24T20:41:28.751Z Traceback (most recent call last):
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/install.py", line 32, in <module>
q5th5 2023-03-24T20:41:28.751Z     download_models()
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/install.py", line 17, in download_models
q5th5 2023-03-24T20:41:28.751Z     hed.HEDdetector()
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/hed/__init__.py", line 103, in __init__
q5th5 2023-03-24T20:41:28.751Z     self.netNetwork = Network(modelpath).cuda().eval()
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 749, in cuda
q5th5 2023-03-24T20:41:28.751Z     return self._apply(lambda t: t.cuda(device))
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
q5th5 2023-03-24T20:41:28.751Z     module._apply(fn)
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
q5th5 2023-03-24T20:41:28.751Z     module._apply(fn)
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
q5th5 2023-03-24T20:41:28.751Z     param_applied = fn(param)
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 749, in <lambda>
q5th5 2023-03-24T20:41:28.751Z     return self._apply(lambda t: t.cuda(device))
q5th5 2023-03-24T20:41:28.751Z   File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
q5th5 2023-03-24T20:41:28.751Z     torch._C._cuda_init()
q5th5 2023-03-24T20:41:28.751Z RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
q5th5 2023-03-24T20:41:29.085Z 
--> ERROR: process "/bin/sh -c cd $HOME/ComfyUI/custom_nodes/comfy_controlnet_preprocessors && python -u install.py" did not complete successfully: exit code: 1

</p>
</CLI Dump>

**Comment by Fannovel16** [comment]
Does your GPU have CUDA cores?

**Comment by paulo-coronado** [comment]
Hello guys! I am having the same issue! @cr4i50n Please DM me if you want to discuss more in detail. My Discord is **pcoronado#4338**

@Fannovel16 Yes, but it seems that the container environment could not use NVIDIA drivers.

**Comment by cr4i50n** [comment]
@paulo-coronado hey any progress on  this problem ?

**Comment by paulo-coronado** [comment]
Hey @cr4i50n! No... not yet... 😢

**Comment by paulo-coronado** [comment]
Okay @cr4i50n! I tested on Runpod's environment and NVIDIA drives worked as expected! I cannot use it on my PC, because it is a pain to setup Docker Container Toolkit and link it with WSL2 and NVIDIA drivers...
