### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2' 

### ISSUE THREAD

**Issue by ronruizG** [Fannovel16/comfy_controlnet_preprocessors#3]
`Traceback (most recent call last):
File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 985, in load_custom_node module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module> from . import canny, hed, midas, mlsd, openpose, uniformer
File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\canny\__init__.py", line 1, in <module> import cv2 ModuleNotFoundError: No module named 'cv2`

Hi I get this error. I've reinstalled opencv and I'm runing the portable version of comfyUI in windows

**Comment by ronruizG** [comment]
I've just copy from my local lib to the one inside "python_embeded" and everything worked
