### ISSUE TITLE
no preProcessor node in the panel

### ISSUE THREAD

**Issue by CactusWang** [Fannovel16/comfy_controlnet_preprocessors#30]
everything goes fine execpt can not find any ControlNet PreProcessors when double-clicking the panel.
pip list showing the openCV-python version is 4.7.0.72, looks CV2 is here

what can I do for this issue?
Appreciate!!

----------
C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Set vram state to: NORMAL_VRAM
Using xformers cross attention
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1119, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from . import canny, hed, midas, mlsd, openpose, uniformer, leres, mp_pose_hand, color, binary, pidinet, mp_face_mesh
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\canny\__init__.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: No module named 'cv2'
Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by Fannovel16** [comment]
I think you used the wrong pip to run install.py. ComfyUI standalone builds use a custom Python build, which means you have to run `/path/to/ComfyUI/python_embeded/python.exe install.py`. Normal `python install.py` command uses Python from the system, not that custom one.
