### ISSUE TITLE
Missing Lib- ModuleNotFoundError: No module named 'basicsr'

### ISSUE THREAD

**Issue by Ideal-Real-Labs** [Fannovel16/comfy_controlnet_preprocessors#32]
Issue when installing

```
comfy_controlnet_preprocessors\v11\pidinet_v11\model.py", line 13, in <module>
    from basicsr.utils import img2tensor
ModuleNotFoundError: No module named 'basicsr'
```

Just tried the latest git clone, this is the issue I get. I'm using the portable version.
Attempted to install package separately to the portable python and got the following error

```
Collecting future (from basicsr)
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-agykw512\future_fba9d1534adf42118674ff3275441cb7\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Fannovel16** [comment]
I forgot to fix lines needing basicsr. The standalone build of ComfyUI can't install basicsr so I have to do it every time I adapt new preprocessors. Do a git pull and it should be fixed now (don't need to install basicsr).
https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/6b073101f75d6ab1e53c231dab8118990fec96ed

**Comment by Ideal-Real-Labs** [comment]
Thanks for sorting so soon. I no longer get this error however I have a new issue when trying to install, URL error. I will post as new issue for you
