### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Ideal-Real-Labs** [Fannovel16/comfy_controlnet_preprocessors#33]
Full error below, this had worked before but not during the latest pull:

```
Downloading: "https://huggingface.co/lllyasviel/Annotators/resolve/dpt_hybrid-midas-501f0c75.pt" to C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\ckpts\dpt_hybrid-midas-501f0c75.pt

Traceback (most recent call last):
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\install.py", line 54, in <module>
    download_models()
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\install.py", line 26, in download_models
    midas.MidasDetector()
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\__init__.py", line 12, in __init__
    self.model = MiDaSInference(model_type="dpt_hybrid").to(model_management.get_torch_device())
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\api.py", line 161, in __init__
    model, _ = load_model(model_type)
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\api.py", line 94, in load_model
    load_file_from_url(remote_model_path, model_dir=annotator_ckpts_path)
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\util.py", line 155, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/752f47c0cec1f5448f0152c7f942c18eaed775d7 and https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/a235b4e3ae5d258151e8fdf8f589337bd737c534

**Comment by Ideal-Real-Labs** [comment]
Nice!
