### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by Ideal-Real-Labs** [Fannovel16/comfy_controlnet_preprocessors#34]
I think I'm close to having this working however there seems to be a library missing, needed for openpose:
After install, then run comfyui, this is the error I get in comfyui terminal:
```

Traceback (most recent call last):
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1246, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from .v1 import canny, hed, midas, mlsd, openpose_v1, uniformer, leres, pidinet_v1
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\openpose_v1\__init__.py", line 6, in <module>
    from . import util
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\openpose_v1\util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

Cannot import C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: No module named 'matplotlib'
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by Fannovel16** [comment]
Git pull this repo then run install.bat

**Comment by Ideal-Real-Labs** [comment]
thanks have tried this, much better idea for use of a install.bat
unfortunately this presents to me a new error when running the install:

```
  File "C:\Portable Program Files\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\../../comfy/model_management.py", line 1, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

**Comment by KumaPlayWithShader** [comment]
File "D:\ComfyUI_Portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\detectron2\utils\env.py", line 87, in _configure_libraries
    import fvcore
ModuleNotFoundError: No module named 'fvcore'

**Comment by GamingDaveUk** [comment]
same issue.
the install.bat just gives me a pyton prompt
ztrl z on that says that it will download models then i get the original error 
if i do python install.py it looks to install stuff but errors out at the end
if i go to the embeded python folder and force install of a few things mentioned in another issue it doesnt seem to fix it but looks to installs some stuff.....  
totally confused now

**Comment by GamingDaveUk** [comment]
even tried runnning the command from the python installed in the pythone embedded folder
![image](https://user-images.githubusercontent.com/131270181/236301619-a4dd34a2-f7c8-48d1-88c1-810e7592d7e3.png)

**Comment by hortom** [comment]
As I see it, the issue is that the generated command has an extra space after the first hyphen:
```
e:\\comfyUI\\python_embeded\\python.exe - s -m pip install -r E:\\comfyUI\\ComfyUI\\custom_nodes\\comfy_controlnet_preprocessors/requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117 --no-warn-script-location
```
Changing line 38 in `install.py` to `    command += ['-s']` solved the issue on my end.

**Comment by Ideal-Real-Labs** [comment]
> As I see it, the issue is that the generated command has an extra space after the first hyphen:
> 
> ```
> e:\\comfyUI\\python_embeded\\python.exe - s -m pip install -r E:\\comfyUI\\ComfyUI\\custom_nodes\\comfy_controlnet_preprocessors/requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117 --no-warn-script-location
> ```
> 
> Changing line 38 in `install.py` to ` command += ['-s']` solved the issue on my end.

Unfortunately didn't work for me. Latest git clone doesn't have this space issue

**Comment by Fannovel16** [comment]
> command += ['-s']

Wait what I'm really confused. Python syntax sucks

**Comment by Ideal-Real-Labs** [comment]
> 

open the install in notepad, go to line 38. see command? Now make sure there is only one space, not two spaces before it, like in the screenshot I shared

**Comment by Fannovel16** [comment]
Gonna make a inline `if` :V
