### ISSUE TITLE
ModuleNotFoundError: No module named 'midas.dpt_depth'

### ISSUE THREAD

**Issue by kenyonxu** [Fannovel16/comfy_controlnet_preprocessors#35]
using git clone build of comfyui:

Traceback (most recent call last):
  File "D:\aiart\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\install.py", line 54, in <module>
    download_models()
  File "D:\aiart\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\install.py", line 32, in download_models
    zoe.ZoeDetector()
  File "D:\AIArt\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\zoe\__init__.py", line 21, in __init__
    model = ZoeDepth.build_from_config(conf)
  File "D:\AIArt\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "D:\AIArt\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "D:\AIArt\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\zoe\zoedepth\models\base_models\midas.py", line 343, in build
    midas = torch.hub.load(midas_path, midas_model_type,
  File "C:\Users\kenyo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\kenyo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 584, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Users\kenyo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\hub.py", line 98, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AIArt\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\zoe\zoedepth\models\base_models\midas_repo\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'midas.dpt_depth'

**Comment by iredmedia** [comment]
My install was previously working as of today this started happening to me too - will post back if i get it - checked all  the files and they exist though, VSCode can click-nav through to them
