### ISSUE TITLE
Getting a runtime error when attempting to use the depth preprocessor.

### ISSUE THREAD

**Issue by teldon** [Fannovel16/comfy_controlnet_preprocessors#5]
Here is the runtime error with the traceback;

Traceback (most recent call last):
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\execution.py", line 174, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\execution.py", line 63, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 121, in estimate_normal
    depth_map_np, normal_map_np = common_annotator_call(midas.MidasDetector(), image, a, bg_threshold)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 16, in common_annotator_call
    call_result = annotator_callback(img_tensor_to_np(tensor_image), *args)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\midas\__init__.py", line 20, in __call__
    depth = self.model(image_depth)[0]
  File "C:\Users\andro\Documents\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\midas\api.py", line 167, in forward
    prediction = self.model(x)
  File "C:\Users\andro\Documents\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\midas\midas\dpt_depth.py", line 108, in forward
    return super().forward(x).squeeze(dim=1)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\midas\midas\dpt_depth.py", line 71, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\midas\midas\vit.py", line 59, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "C:\Users\andro\Documents\Stable Diffusion\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\midas\midas\vit.py", line 145, in forward_flex
    x = x + pos_embed
RuntimeError: The size of tensor a (4001) must match the size of tensor b (3921) at non-singleton dimension 1

**Comment by Fannovel16** [comment]
It maybe a image size problem. Try to resize your images to the resolution whose width and height are multiples of 64.

**Comment by teldon** [comment]
That seems to have been the problem. Might be worth mentioning that on the main page.

**Comment by Fannovel16** [comment]
Edited the main page
https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/0ae18f03ec2b6e9411ce9d35e22576997b9bf666

**Comment by Fannovel16** [comment]
@teldon You don't need to resize the images now since I added some lines of code to do it internally: https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/30ad8ae8b128cd253172b24b6ce98421f36588c7

**Comment by teldon** [comment]
Even better!
