### ISSUE TITLE
Install fails due to missing "ftfy' module

### ISSUE THREAD

**Issue by harshbarger** [Fannovel16/comfy_controlnet_preprocessors#56]
When I attempt to install, I consistently get stopped by a missing module. Any ideas would be greatly appreciated.

1. I have already tried running `update_comfyui_and_python_dependencies.bat`. 
2. I was running the install script with the `python.exe` from the `python_embeded` folder, as instructed for the portable version.

Output from attempt: 

... lots of Requirement Already Satisfied lines 

Total VRAM 4096 MB, total RAM 32694 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.20
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650

Traceback (most recent call last):
  File "C:\Users\donov\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\install.py", line 53, in <module>
    add_global_shortcut_module(this_module_name, os.path.join(EXT_PATH, "__init__.py"))

... more intermediate calls

  File "C:\Users\donov\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\oneformer\oneformer_model.py", line 24, in <module>
    from comfy_controlnet_preprocessors.v11.oneformer.oneformer.data.tokenizer import SimpleTokenizer, Tokenize
  File "C:\Users\donov\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\oneformer\data\tokenizer.py", line 32, in <module>
    import ftfy
ModuleNotFoundError: No module named 'ftfy'

**Comment by harshbarger** [comment]
Update: I now have the install completed, and I can add the preprocessing nodes. I downloaded the tarball for the `ftfy` module and copied the `ftfy` folder into the python_embedding/Lib/site-packages folder, since that's where the `torch` module imported in the same file was.

However, I don't know a hill of beans about structuring portable Python projects, and I'm not sure if this is where it truly belongs. Is this the right spot, or does it belong someplace else since it seems to be used only by this particular custom node rather than ComfyUI in general?

**Comment by nyukers** [comment]
Same error to me in Colab. I did **!pip install ftfy** manually, but it didn't resolve the problem. I have next error about main module don`t define(.

**Comment by amir84ferdos** [comment]
I have the same problem for installing on portable version :(

**Comment by amir84ferdos** [comment]
change the config.yaml before installing to this and then it will work: 

 # where are the ckpts stored?
#annotator_ckpts_path: "R:\\controlnet_pre_ckpts\\ckpts"
skip_v1: False
annotator_ckpts_path: "./ckpts"

**Comment by CoraAI** [comment]
> change the config.yaml before installing to this and then it will work:
> 
> # where are the ckpts stored?
> #annotator_ckpts_path: "R:\controlnet_pre_ckpts\ckpts" skip_v1: False annotator_ckpts_path: "./ckpts"

got same problem and tried this but not work, problem remains the same. shall I install from the very beginning?

**Comment by TimothyKrell** [comment]
Easier way to fix this until #63 gets merged is to add `ftfy` to the end of `requirements.txt`

**Comment by jjangga0214** [comment]
The PR #63 is merged. You or @Fannovel16 can close this.
