### ISSUE TITLE
fix: `MiDaS-NormalMapPreprocessor` is shown in UI but not defined when using v1.1

### ISSUE THREAD

**Issue by jjangga0214** [Fannovel16/comfy_controlnet_preprocessors#65]
It's available on UI, but causing an error as not imported when using v1.1.

```
Error occurred when executing MiDaS-NormalMapPreprocessor:  name 'midas' is not defined  File "/Users/ocean/main/ComfyUI/execution.py", line 141, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/Users/ocean/main/ComfyUI/execution.py", line 75, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/Users/ocean/main/ComfyUI/execution.py", line 68, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/nodes/normal_depth_map.py", line 42, in estimate_normal depth_map_np, normal_map_np = common_annotator_call(midas.MidasDetector(), image, a, bg_threshold)
```

https://github.com/Fannovel16/comfy_controlnet_preprocessors/blob/b0c04a2a48699e41fff2e6ceba6c61940ca68545/nodes/normal_depth_map.py#L2-L3

**Comment by mattfoxley** [comment]
Any luck with a fix for this yet? I'm running into the same issue even after clean install and haven't been able to figure out how to get Midas to work...

**Comment by minimerce** [comment]
Would love to hear about a solution as well.

**Comment by alexbofa** [comment]
Hello, I have the same problem
```bat
Params passed to Resize transform:
        width:  512
        height:  384
        resize_target:  True
        keep_aspect_ratio:  True
        ensure_multiple_of:  32
        resize_method:  minimal
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\normal_depth_map.py", line 42, in estimate_normal
    depth_map_np, normal_map_np = common_annotator_call(midas.MidasDetector(), image, a, bg_threshold)
NameError: name 'midas' is not defined
```

**Comment by moon47usaco** [comment]
I do not get any error on console but the processed image is all black.
![Screenshot 2023-08-16 032041](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/15712871/53371316-44ca-4202-a34f-ba248baf282e)

**Comment by Yorha4D** [comment]
@alexbofa In fact, in addition to this, FakeScribble will also report errors. I studied the code carefully and found that the author added a V1_SKIP function that is enabled by default. However, in some places, the judgment code is reversed, causing some functions to be unavailable regardless of whether this function is enabled or not. For example, FakeScribble will be unavailable because HED V1 is unavailable....

**Comment by alexbofa** [comment]
> @alexbofa In fact, in addition to this, FakeScribble will also report errors. I studied the code carefully and found that the author added a V1_SKIP function that is enabled by default. However, in some places, the judgment code is reversed, causing some functions to be unavailable regardless of whether this function is enabled or not. For example, FakeScribble will be unavailable because HED V1 is unavailable....

Hello, yes it's work when I write `skip_v1: False` in file [config.yaml](https://github.com/Fannovel16/comfy_controlnet_preprocessors/blob/main/config.yaml.example) / https://github.com/Fannovel16/comfy_controlnet_preprocessors/issues/96#issue-1851461463

Thanks

**Comment by Yorha4D** [comment]
> > @alexbofa In fact, in addition to this, FakeScribble will also report errors. I studied the code carefully and found that the author added a V1_SKIP function that is enabled by default. However, in some places, the judgment code is reversed, causing some functions to be unavailable regardless of whether this function is enabled or not. For example, FakeScribble will be unavailable because HED V1 is unavailable....
> 
> Hello, yes it's work when I write `skip_v1: False` in file [config.yaml](https://github.com/Fannovel16/comfy_controlnet_preprocessors/blob/main/config.yaml.example) / [#96 (comment)](https://github.com/Fannovel16/comfy_controlnet_preprocessors/issues/96#issuecomment-1679453527)
> 
> Thanks

I am currently working on multilingual translation for COMFYUI, and I really don't have time to submit a fix for this. I hope everything goes smoothly for you~
