### ISSUE TITLE
fix:  `Zoe-DepthMapPreprocessor` TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.int64'>, <class 'numpy.int64'>]

### ISSUE THREAD

**Issue by jjangga0214** [Fannovel16/comfy_controlnet_preprocessors#66]
When using `Zoe-DepthMapPreprocessor`, an error occurs.

```bash
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/ocean/main/ComfyUI/execution.py", line 141, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/ocean/main/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/ocean/main/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/nodes/normal_depth_map.py", line 79, in estimate_depth
    np_detected_map = common_annotator_call(zoe.ZoeDetector(), image)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/nodes/util.py", line 24, in common_annotator_call
    call_result = annotator_callback(resize_image(HWC3(tensor_image)), *args)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/__init__.py", line 34, in __call__
    depth = self.model.infer(image_depth)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/depth_model.py", line 126, in infer
    return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/depth_model.py", line 110, in infer_with_flip_aug
    out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/depth_model.py", line 88, in _infer_with_pad_aug
    out = self._infer(x)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/depth_model.py", line 55, in _infer
    return self(x)['metric_depth']
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 144, in forward
    rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/base_models/midas.py", line 263, in forward
    x = self.prep(x)
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/base_models/midas.py", line 187, in __call__
    return self.normalization(self.resizer(x))
  File "/Users/ocean/main/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/zoe/zoedepth/models/base_models/midas.py", line 174, in __call__
    return nn.functional.interpolate(x, (height, width), mode='bilinear', align_corners=True)
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/functional.py", line 3928, in interpolate
    raise TypeError(
TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.int64'>, <class 'numpy.int64'>]
```

**Info**:

OS: macOS Ventura 13.4.1 (22F82)
HW: Apple M1 Max
python: 3.10.10
pip: 23.0.1
env: a miniconda environment dedicated to only ComfyUI

**Comment by jjangga0214** [comment]
Closing as the PR merged.
