### ISSUE TITLE
Install error: name 'model_management' is not defined

### ISSUE THREAD

**Issue by cubiq** [Fannovel16/comfy_controlnet_preprocessors#68]
During installation I get the following error

```
Traceback (most recent call last):
  File "/home/matteo/bin/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/install.py", line 58, in <module>
    download_models()
  File "/home/matteo/bin/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/install.py", line 27, in download_models
    midas.MidasDetector()
  File "/home/matteo/bin/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v1/midas/__init__.py", line 12, in __init__
    self.model = MiDaSInference(model_type="dpt_hybrid").to(model_management.get_torch_device())
                                                            ^^^^^^^^^^^^^^^^
NameError: name 'model_management' is not defined
```

Any insight?

**Comment by CoraAI** [comment]
I got exactly the same error trying the MiDaS-DepthMap preprocesser node.

Error occurred when executing MiDaS-DepthMapPreprocessor:

name 'model_management' is not defined

File "D:\Ai_program\comfyUI\ComfyUI\execution.py", line 141, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\Ai_program\comfyUI\ComfyUI\execution.py", line 75, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\Ai_program\comfyUI\ComfyUI\execution.py", line 68, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\Ai_program\comfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\normal_depth_map.py", line 23, in estimate_depth
depth_map_np, normal_map_np = common_annotator_call(midas.MidasDetector(), image, a, bg_threshold)
File "D:\Ai_program\comfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\__init__.py", line 12, in __init__
self.model = MiDaSInference(model_type="dpt_hybrid").to(model_management.get_torch_device())

**Comment by cubiq** [comment]
turns out there's already a PR fixing this issue https://github.com/Fannovel16/comfy_controlnet_preprocessors/pull/59
