### ISSUE TITLE
TypeError: A Message class can only inherit from Message

### ISSUE THREAD

**Issue by DanJanz** [Fannovel16/comfy_controlnet_preprocessors#70]
I have been trying desperately for 2 days to install these notes, but I always encounter the same error. This occurs when starting ConfyUi. However, I don't get any errors when installing. I have already tested different compatible versions of mediapipe and protobuf, but without success. The import always fails.
Installed onto the latest portable version of ComfyUI.
Here is my traceback:

Traceback (most recent call last):

  File "G:\ComfyUI\ComfyUI\nodes.py", line 1456, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "G:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "G:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\pose.py", line 5, in <module>
    from .. import mp_pose_hand
  File "G:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\mp_pose_hand\__init__.py", line 2, in <module>
    import mediapipe as mp
  File "G:\ComfyUI\python_embeded\lib\site-packages\mediapipe\__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "G:\ComfyUI\python_embeded\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "G:\ComfyUI\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "G:\ComfyUI\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "G:\ComfyUI\python_embeded\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "G:\ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1855, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.descriptor_pb2', globals())
  File "G:\ComfyUI\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "G:\ComfyUI\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
TypeError: A Message class can only inherit from Message

Cannot import G:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: A Message class can only inherit from Message

**Comment by Piscabo** [comment]
I have the same problem... No answer yet.

**Comment by dougwhite** [comment]
> It worked when I upgraded the version of mediapipe==0.10.2

A combination of this suggestion and remaking my environment manually (as opposed to the portable version) fixed the issue for me.

**Comment by Piscabo** [comment]
> > It worked when I upgraded the version of mediapipe==0.10.2
> 
> Thanks very much for this. A combination of this suggestion and remaking my environment manually with virtualenv (as opposed to just using the portable version) fixed the issue for me.

Will this not clash with an existing install that has a /venv already? (SD Auotomatic1111)

**Comment by dougwhite** [comment]
> Will this not clash with an existing install that has a /venv already? (SD Auotomatic1111)

I'm not sure, very noob at python, but I can tell you what I did if that helps...

I was using the portable version and kept having dependency issues, so I cloned the repo to a fresh folder and followed the manual installation instructions from scratch. First I tried to set up virtualenv and discovered that my python installation had been corrupted, so truthfully i started by purging python/pip/pip cache/%appdata% cruft etc from my pc completely.

Then I re-installed python, then pipx, then virtualenv, and created a new virtual environment under the new ComfyUi folder: `ComfyUI/venv`

I followed the manual installation instructions in the README.md, and then began installing extensions one at a time. I decided to install the extensions manually and slowly to ensure each step worked. I installed 3-4 extensions with the model manager, as they were simple and had worked previously without issues, but the rest I just followed whatever manual instructions were on that extensions repo.

When I went to install controlnet I modified requirements.txt to use `mediapipe==0.10.2` as suggested by forestsource. I also changed `install.py` to do a `pip --dry-run`; just so I could check everything was hunky-doory. When i was satisfied I ran the installation proper and it all worked fine.

Did the same thing for some other extensions that were causing me problems, i.e follow any manual install guides on their repos, do them 1 at a time. Occasionally I had to `pip install` a package manually (e.g comfy_mtb needed some face restoration package). Apart from that everything worked first try, no issues. Except....

When I went to use Automatic1111 I realised I had borked the virtualenv as it was pointing to my previous python installation. However after deleting the Automatic1111 virtualenv and re-running `webui-user.bat` it magically healed itself.

I initially forgot to deactivate comfy's virtualenv, and automatic1111 tried to bootstrap itself from comfy... but I decided I wanted the two environments to remain separate so unfortunately I can't tell you how well it would work when shared between the two.

But yeah after a clean manual install + the fix suggested by forestsource + setting up virtualenvs correctly, I have had 0 issues or conflicts and both Comfyui and Automatic1111 are working fine.

Like I said I'm fairly inexperienced with all this python business, but yeah hopefully that all makes sense.

**Comment by zhulinyv** [comment]
〒▽〒

I have the same problem, and I do not know how to solve it.

I tried to reinstall **mediapipe** and all the requirements of comfy_controlnet_preprocessors, but it doesn't work on my PC.

Maybe the problem caused by the virtualenv, but I really do not want to delete it, because I have many custom_nodes which need a lot of requirements...

Python: 3.10.9
System: Windows11
ComfyUI: portable standalone build

![image](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/66541860/22965efb-d7ec-4182-a741-00305dbf69d4)

**Comment by zhulinyv** [comment]
> 〒▽〒
> 
> I have the same problem, and I do not know how to solve it.
> 
> I tried to reinstall **mediapipe** and all the requirements of comfy_controlnet_preprocessors, but it doesn't work on my PC.
> 
> Maybe the problem caused by the virtualenv, but I really do not want to delete it, because I have many custom_nodes which need a lot of requirements...
> 
> Python: 3.10.9 System: Windows11 ComfyUI: portable standalone build
> 
> [![image](https://user-images.githubusercontent.com/66541860/256988966-22965efb-d7ec-4182-a741-00305dbf69d4.png)](javascript:void(0))

I think I know why this error occurs, comfy_controlnet_preprocessors cannot be loaded with [ComfyUI_roop](https://github.com/Navezjt/ComfyUI_roop), If I don't use one of them, then the other works fine, the main reason may be this comment: https://github.com/protocolbuffers/protobuf/issues/3276#issuecomment-566811649

![image](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/66541860/d2053937-b576-4b0c-b29f-9f61240f3419)
![image](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/66541860/78e65e2a-aff8-494c-8b67-5e7ca86f89bc)

**Comment by Piscabo** [comment]
@zhulinyv 
I'm using an active venv now and all my problems went away. I had SD A1111 installed and thought it already have an environment and I can run both installs now.  So if you already have Venv, use that in your batch start. Move comfy out of the standalone folders. This way you save a lot of drive space.
@echo off
_REM Set the path to the virtual environment_
set VENV_PATH=*:\*\stable-diffusion-webui\venv
_REM Activate the virtual environment_
call %VENV_PATH%\Scripts\activate
REM Run the Python script
python main.py --use-pytorch-cross-attention --normalvram
REM Pause to keep the command prompt window open
pause
REM Deactivate the virtual environment
call %VENV_PATH%\Scripts\deactivate
*  change to your path

**Comment by zhulinyv** [comment]
> @zhulinyv I'm using an active **venv** now and all my problems went away. I had SD A1111 installed and thought it already have an environment and I can run both installs now. So if you already have **venv**, use that in your batch start for Comfy. Move comfy out of the standalone folders. This way you save a lot of drive space. ( you can even run both apps, but don't render at the same time... pc burnout!) @echo off _REM Set the path to the virtual environment_ set VENV_PATH=*:*\stable-diffusion-webui\venv _REM Activate the virtual environment_ call %VENV_PATH%\Scripts\activate _REM Run the Python script_ python main.py --use-pytorch-cross-attention --normalvram _REM Pause to keep the command prompt window open_ pause _REM Deactivate the virtual environment_ call %VENV_PATH%\Scripts\deactivate
> 
> * change to your path

Thanks for your reply, 



Now my problem is solved.🥰

**Comment by DanJanz** [comment]
> As said above, it is because of conflicts with Roop, but I'm not sure where to report issues for that project. As mentioned in the protobuf bug, it has to do with load orders and things getting loaded twice. I fixed it with a hack inside of Comfy's `nodes.py`:
> 
> ```python
> def load_custom_nodes():
>     base_node_names = set(NODE_CLASS_MAPPINGS.keys())
>     node_paths = folder_paths.get_folder_paths("custom_nodes")
>     node_import_times = []
>     for custom_node_path in node_paths:
>         possible_modules = os.listdir(custom_node_path)
>         if "__pycache__" in possible_modules:
>             possible_modules.remove("__pycache__")
> 
>         # HACK: Force roop to load after controlnet preprocessors.
>         if 'ComfyUI_roop' in possible_modules:
>             possible_modules.remove('ComfyUI_roop')
>             possible_modules.append('ComfyUI_roop')
>         print(possible_modules)
> ```
> 
> This works for me with a default ComfyUI installed via venv (not portable).

Can confirm this hack also working on the portable version.
