### ISSUE TITLE
ImportError: cannot import name 'builder' from 'google.protobuf.internal'

### ISSUE THREAD

**Issue by za-wa-n-go** [Fannovel16/comfy_controlnet_preprocessors#75]
Traceback (most recent call last):
  File "C:\Product\ComfyUI\nodes.py", line 1509, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "C:\Product\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "C:\Product\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\pose.py", line 5, in <module>
    from .. import mp_pose_hand
  File "C:\Product\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\mp_pose_hand\__init__.py", line 2, in <module>
    import mediapipe as mp
  File "C:\Product\ComfyUI\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Product\ComfyUI\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Product\ComfyUI\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Product\ComfyUI\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Product\ComfyUI\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Product\ComfyUI\venv\lib\site-packages\google\protobuf\internal\__init__.py)

Cannot import C:\Product\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: cannot import name 'builder' from 'google.protobuf.internal' (C:\Product\ComfyUI\venv\lib\site-packages\google\protobuf\internal\__init__.py)

**Comment by za-wa-n-go** [comment]
https://github.com/melMass/comfy_mtb

↑This occurs as a result of installing the custom node up.
To deal with this, I set protobuf to 3.20.3 and preprocessor can be imported, but there seems to be a dependency mismatch with the one installed by mtb.
Can this be resolved?
Is it correct that mtb and preprocessor should not be mixed...?

**Comment by melMass** [comment]
This should have been fixed in https://github.com/melMass/comfy_mtb/commit/1a92ef734dd4271efc875856038f9e3b6b9ded6c

The is still a conflict between our two projects on google colab though ( https://github.com/melMass/comfy_mtb/issues/18 ) but it should be minimal to fix on my side :)

**Comment by airtisticchad** [comment]
@melMass It still doesn't work for me.

**Comment by wertos97** [comment]
I'm currently facing the same exact issue, however removing all the other extensions (uninstalling, leaving only the Manager and the ControlNet Preprocessors) still gives the following error:

```
Traceback (most recent call last):
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\pose.py", line 5, in <module>
    from .. import mp_pose_hand
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\mp_pose_hand\__init__.py", line 2, in <module>
    import mediapipe as mp
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\__init__.py)

Cannot import C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\__init__.py)
```

**Comment by melMass** [comment]
The issue is coming from the old version of tensorflow comfymtb has to use on windows (they removed GPU support after this version and for some operations I use it's 10-60x faster on GPU

The version of protobuf that seems the most compatible is 3.19.6:

python_embedded/python.exe -m pip install  protobuf==3.19.6

**Comment by wertos97** [comment]
Thank you for your answer. Turns out, for some reason the embedded python was entirely missing the `builder.py` file. 

I have solved the problem by simply copying said file from the system's python instance (`C:\Users\wertos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\google\protobuf\internal\builder.py`) to the embedded env (`C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\google\protobuf\internal`). 

I hope this helps the next person having this problem.

With both ControlNet Preprocessors and ComfyMTB installed, I still get an error but I assume it's safe to ignore it (for now). Traceback below:

```  File "logging\__init__.py", line 1103, in emit
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 24, in write
    self.file.write(message)
  File "encodings\cp1250.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 476: character maps to <undefined>
Call stack:
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\main.py", line 145, in <module>
    init_custom_nodes()
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1700, in init_custom_nodes
    load_custom_nodes()
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1677, in load_custom_nodes
    success = load_custom_node(module_path, base_node_names)
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\wertos\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 173, in <module>
    log.info(
  File "logging\__init__.py", line 1477, in info
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\__init__.py", line 1108, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.```

**Comment by alexbofa** [comment]
@wertos97 Hello

Hm, is this a similar error?
https://github.com/ltdrdata/ComfyUI-Manager/issues/64
