### ISSUE TITLE
Loading this extension somehow caused an error in the k-sampler | OSError: [WinError 6] 句柄无效  

### ISSUE THREAD

**Issue by RuaYiii** [Fannovel16/comfy_controlnet_preprocessors#76]
Loading this extension somehow caused an error in the k-sampler, after removing the extension, everything worked fine!
Load the extension without adding the nodes related to the extension.

The full error report is as follows： 
```
Prompt executed in 0.03 seconds
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\git_project\ComfyUI-master\ComfyUI-master\execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\git_project\ComfyUI-master\ComfyUI-master\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\git_project\ComfyUI-master\ComfyUI-master\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\git_project\ComfyUI-master\ComfyUI-master\nodes.py", line 1079, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "E:\git_project\ComfyUI-master\ComfyUI-master\nodes.py", line 1049, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\git_project\ComfyUI-master\ComfyUI-master\comfy\sample.py", line 88, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\git_project\ComfyUI-master\ComfyUI-master\comfy\samplers.py", line 670, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "C:\tools\Anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\git_project\ComfyUI-master\ComfyUI-master\comfy\k_diffusion\sampling.py", line 234, in sample_dpm_2_ancestral
    for i in trange(len(sigmas) - 1, disable=disable):
  File "C:\tools\Anaconda3\lib\site-packages\tqdm\auto.py", line 37, in trange
    return tqdm(range(*args), **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\tqdm\asyncio.py", line 24, in __init__
    super(tqdm_asyncio, self).__init__(iterable, *args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\tqdm\std.py", line 1093, in __init__
    self.sp = self.status_printer(self.fp)
  File "C:\tools\Anaconda3\lib\site-packages\tqdm\std.py", line 336, in status_printer
    getattr(sys.stderr, 'flush', lambda: None)()
OSError: [WinError 6] 句柄无效。

Prompt executed in 0.03 seconds
```

**Comment by RuaYiii** [comment]
After configuring the environment from scratch on the company's computer, the mismatch does not occur, but the error report does not show the exact problem (the current discrepancy is that the machine with the error is Win11, while the company's computer is Win10).

I don't know how to fix it 😭😭😭😭
