### ISSUE TITLE
[error]HED V1 

### ISSUE THREAD

**Issue by Yorha4D** [Fannovel16/comfy_controlnet_preprocessors#83]
@Fannovel16 When I use hed v1, I receive the error 'hed_v1 undefined'

**Comment by alexbofa** [comment]
Hello, I have the same problem and with [MiDaS-NormalMapPreprocessor](https://github.com/Fannovel16/comfy_controlnet_preprocessors/issues/65#issuecomment-1678830208)
```bat
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\edge_line.py", line 89, in transform_scribble
    np_detected_map_list = common_annotator_call(hed_v1.HEDdetector(), image)
NameError: name 'hed_v1' is not defined```
![image](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/58225118/6d956612-c5d7-4fe9-8645-6e747b264615)
