### ISSUE TITLE
Error at ComfyUI portable launching on ControlNet preprocessors, help :)

### ISSUE THREAD

**Issue by MattRM2** [Fannovel16/comfy_controlnet_preprocessors#86]
Hi,

I tried to install the comfy_controlnet_preprocessors and when I launch ComfyUI portable, I have errors. It seems no errors during installation but error when launching it. Below, the logs from the install and when launching ComfyUI.

Install logs : 
`E:\00_ComfyUI\ComfyUI\custom_nodes>cd comfy_controlnet_preprocessors

E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors>install --no_download_ckpts
Custom Python build of ComfyUI standalone executable detected:
"E:\00_ComfyUI\python_embeded\python.exe"
--------------------------------------------------
Installing requirements...
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Requirement already satisfied: opencv-contrib-python in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 1)) (4.8.0.74)
Requirement already satisfied: opencv-python in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 2)) (4.7.0.72)
Requirement already satisfied: timm==0.6.7 in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (0.6.7)
Requirement already satisfied: torchvision in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (0.15.2+cu118)
Requirement already satisfied: scipy in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 5)) (1.11.1)
Requirement already satisfied: matplotlib in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (3.7.2)
Requirement already satisfied: scikit-image in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 7)) (0.21.0)
Requirement already satisfied: prettytable==3.6.0 in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 8)) (3.6.0)
Requirement already satisfied: addict in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 9)) (2.4.0)
Requirement already satisfied: yapf in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 10)) (0.40.1)
Requirement already satisfied: mediapipe in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (0.10.2)
Requirement already satisfied: fvcore in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (0.1.5.post20221221)
Requirement already satisfied: omegaconf in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 13)) (2.3.0)
Requirement already satisfied: ftfy in e:\00_comfyui\python_embeded\lib\site-packages (from -r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 14)) (6.1.1)
Requirement already satisfied: torch>=1.4 in e:\00_comfyui\python_embeded\lib\site-packages (from timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (2.0.1+cu118)
Requirement already satisfied: wcwidth in e:\00_comfyui\python_embeded\lib\site-packages (from prettytable==3.6.0->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 8)) (0.2.6)
Requirement already satisfied: numpy>=1.21.2 in e:\00_comfyui\python_embeded\lib\site-packages (from opencv-contrib-python->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 1)) (1.24.4)
Requirement already satisfied: requests in e:\00_comfyui\python_embeded\lib\site-packages (from torchvision->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in e:\00_comfyui\python_embeded\lib\site-packages (from torchvision->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (9.5.0)
Requirement already satisfied: filelock in e:\00_comfyui\python_embeded\lib\site-packages (from torch>=1.4->timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (3.12.2)
Requirement already satisfied: typing-extensions in e:\00_comfyui\python_embeded\lib\site-packages (from torch>=1.4->timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (4.7.0)
Requirement already satisfied: sympy in e:\00_comfyui\python_embeded\lib\site-packages (from torch>=1.4->timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (1.12)
Requirement already satisfied: networkx in e:\00_comfyui\python_embeded\lib\site-packages (from torch>=1.4->timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (3.1)
Requirement already satisfied: jinja2 in e:\00_comfyui\python_embeded\lib\site-packages (from torch>=1.4->timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in e:\00_comfyui\python_embeded\lib\site-packages (from matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: cycler>=0.10 in e:\00_comfyui\python_embeded\lib\site-packages (from matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in e:\00_comfyui\python_embeded\lib\site-packages (from matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (4.41.0)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\00_comfyui\python_embeded\lib\site-packages (from matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in e:\00_comfyui\python_embeded\lib\site-packages (from matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (23.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in e:\00_comfyui\python_embeded\lib\site-packages (from matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in e:\00_comfyui\python_embeded\lib\site-packages (from matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (2.8.2)
Requirement already satisfied: imageio>=2.27 in e:\00_comfyui\python_embeded\lib\site-packages (from scikit-image->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 7)) (2.31.1)
Requirement already satisfied: tifffile>=2022.8.12 in e:\00_comfyui\python_embeded\lib\site-packages (from scikit-image->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 7)) (2023.7.18)
Requirement already satisfied: PyWavelets>=1.1.1 in e:\00_comfyui\python_embeded\lib\site-packages (from scikit-image->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 7)) (1.4.1)
Requirement already satisfied: lazy_loader>=0.2 in e:\00_comfyui\python_embeded\lib\site-packages (from scikit-image->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 7)) (0.3)
Requirement already satisfied: importlib-metadata>=6.6.0 in e:\00_comfyui\python_embeded\lib\site-packages (from yapf->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 10)) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in e:\00_comfyui\python_embeded\lib\site-packages (from yapf->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 10)) (3.9.1)
Requirement already satisfied: tomli>=2.0.1 in e:\00_comfyui\python_embeded\lib\site-packages (from yapf->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 10)) (2.0.1)
Requirement already satisfied: absl-py in e:\00_comfyui\python_embeded\lib\site-packages (from mediapipe->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (1.4.0)
Requirement already satisfied: attrs>=19.1.0 in e:\00_comfyui\python_embeded\lib\site-packages (from mediapipe->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (23.1.0)
Requirement already satisfied: flatbuffers>=2.0 in e:\00_comfyui\python_embeded\lib\site-packages (from mediapipe->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (23.5.26)
Requirement already satisfied: protobuf<4,>=3.11 in e:\00_comfyui\python_embeded\lib\site-packages (from mediapipe->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (3.20.3)
Requirement already satisfied: sounddevice>=0.4.4 in e:\00_comfyui\python_embeded\lib\site-packages (from mediapipe->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (0.4.6)
Requirement already satisfied: yacs>=0.1.6 in e:\00_comfyui\python_embeded\lib\site-packages (from fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (0.1.8)
Requirement already satisfied: pyyaml>=5.1 in e:\00_comfyui\python_embeded\lib\site-packages (from fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (6.0)
Requirement already satisfied: tqdm in e:\00_comfyui\python_embeded\lib\site-packages (from fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (4.65.0)
Requirement already satisfied: termcolor>=1.1 in e:\00_comfyui\python_embeded\lib\site-packages (from fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (2.3.0)
Requirement already satisfied: tabulate in e:\00_comfyui\python_embeded\lib\site-packages (from fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (0.9.0)
Requirement already satisfied: iopath>=0.1.7 in e:\00_comfyui\python_embeded\lib\site-packages (from fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (0.1.10)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in e:\00_comfyui\python_embeded\lib\site-packages (from omegaconf->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 13)) (4.9.3)
Requirement already satisfied: zipp>=0.5 in e:\00_comfyui\python_embeded\lib\site-packages (from importlib-metadata>=6.6.0->yapf->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 10)) (3.16.2)
Requirement already satisfied: portalocker in e:\00_comfyui\python_embeded\lib\site-packages (from iopath>=0.1.7->fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (2.7.0)
Requirement already satisfied: six>=1.5 in e:\00_comfyui\python_embeded\lib\site-packages (from python-dateutil>=2.7->matplotlib->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: CFFI>=1.0 in e:\00_comfyui\python_embeded\lib\site-packages (from sounddevice>=0.4.4->mediapipe->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (1.15.1)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\00_comfyui\python_embeded\lib\site-packages (from requests->torchvision->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in e:\00_comfyui\python_embeded\lib\site-packages (from requests->torchvision->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\00_comfyui\python_embeded\lib\site-packages (from requests->torchvision->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in e:\00_comfyui\python_embeded\lib\site-packages (from requests->torchvision->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (2023.5.7)
Requirement already satisfied: colorama in e:\00_comfyui\python_embeded\lib\site-packages (from tqdm->fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (0.4.6)
Requirement already satisfied: pycparser in e:\00_comfyui\python_embeded\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 11)) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in e:\00_comfyui\python_embeded\lib\site-packages (from jinja2->torch>=1.4->timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (2.1.3)
Requirement already satisfied: pywin32>=226 in e:\00_comfyui\python_embeded\lib\site-packages (from portalocker->iopath>=0.1.7->fvcore->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 12)) (306)
Requirement already satisfied: mpmath>=0.19 in e:\00_comfyui\python_embeded\lib\site-packages (from sympy->torch>=1.4->timm==0.6.7->-r E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 3)) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063`

During ComfyUI portable startup : 
`E:\00_ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build

Prestartup times for custom nodes:
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65436 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1070 Ti : native
Using xformers cross attention
Adding extra search path checkpoints E:\00_Automatic1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs E:\00_Automatic1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae E:\00_Automatic1111\stable-diffusion-webui\models/VAE
Adding extra search path loras E:\00_Automatic1111\stable-diffusion-webui\models/Lora
Adding extra search path loras E:\00_Automatic1111\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models E:\00_Automatic1111\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models E:\00_Automatic1111\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models E:\00_Automatic1111\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings E:\00_Automatic1111\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks E:\00_Automatic1111\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet E:\00_Automatic1111\stable-diffusion-webui\extensions/sd-webui-controlnet/models
Bmad-DirtyUndoRedo Loaded.
### ComfyUI Revision: 1218 [c910b4a0]
OpenPose Editor: Loaded
Davemane42 Custom Nodes: Loaded
2023-07-29 11:16:38,243 - roop - INFO - roop v0.0.2
Traceback (most recent call last):
  File "E:\00_ComfyUI\ComfyUI\nodes.py", line 1596, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\pose.py", line 5, in <module>
    from .. import mp_pose_hand
  File "E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\mp_pose_hand\__init__.py", line 2, in <module>
    import mediapipe as mp
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 14, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 14, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 20, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediapipe.framework.formats.annotation.rasterization_pb2', _globals)
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 82, in BuildMessage
    create_dict[name] = BuildMessage(nested_msg)
  File "E:\00_ComfyUI\python_embeded\lib\site-packages\google\protobuf\internal\builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
TypeError: A Message class can only inherit from Message

Cannot import E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: A Message class can only inherit from Message

Import times for custom nodes:
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.6 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI_roop
   1.2 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\rembg-comfyui-node
   1.4 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   1.5 seconds (IMPORT FAILED): E:\00_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
   3.4 seconds: E:\00_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188`

I hope you'll can help me to solve it, it's the only module I can't use so need to run A1111 for that but I prefer ComfyUI.
Also, one other question, do you support in your preprocessors the inpaint+lama ?

Thank you in advance for your help,
PS : If you need more information on my version, just ask me.

Matt

**Comment by BoosterCore** [comment]
same error here, Conflict with ComfyUI_Roop, when disable Roop, controlnet_preprocessors can be import again... hope new update wil fix it.

**Comment by MattRM2** [comment]
> same error here, Conflict with ComfyUI_Roop, when disable Roop, controlnet_preprocessors can be import again... hope new update wil fix it.

I updated ComfyUI and all custom nodes yesterday and all working fine now. Just the Roop from Reactor-node do the error now. Updated everything from the manager node (I have the portable ComfyUI).

If it can help ;)

Matt

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues/2#issuecomment-1666481956

**Comment by MattRM2** [comment]
> [Gourieff/comfyui-reactor-node#2 (comment)](https://github.com/Gourieff/comfyui-reactor-node/issues/2#issuecomment-1666481956)

Hi Gourieff,

Thank you very much for your link and the answer ;)

Matt
