### ISSUE TITLE
Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: No module named 'timm'

### ISSUE THREAD

**Issue by vxkj1211** [Fannovel16/comfy_controlnet_preprocessors#92]
### ComfyUI Revision: 1267 [5e2b4893]
OpenPose Editor: Loaded
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\edge_line.py", line 1, in <module>
    from .util import common_annotator_call, img_np_to_tensor, img_tensor_to_np, skip_v1
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\util.py", line 1, in <module>
    from ..v1 import openpose_v1, midas
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\__init__.py", line 6, in <module>
    from .api import MiDaSInference
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\api.py", line 9, in <module>
    from .midas.dpt_depth import DPTDepthModel
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\midas\dpt_depth.py", line 6, in <module>
    from .blocks import (
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\midas\blocks.py", line 4, in <module>
    from .vit import (
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\midas\midas\vit.py", line 3, in <module>
    import timm
ModuleNotFoundError: No module named 'timm'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: No module named 'timm'

**Comment by vukimvung** [comment]
same error in google colab :(

**Comment by uarefans** [comment]
try D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
click install.bat

**Comment by vukimvung** [comment]
> try open directory D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors click install.bat

How to fix in Google Coleb bro ??
