### ISSUE TITLE
Import error for module 'pywintypes'

### ISSUE THREAD

**Issue by poornapragnarao** [Fannovel16/comfy_controlnet_preprocessors#95]
Installed through Comfyui Manager, getting this error - 

`### Loading: ComfyUI-Impact-Pack (V3.12.1)
### ComfyUI Revision: 1274 [2bc12d3d]
Traceback (most recent call last):
  File "<mypath>\comfyui\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\semseg.py", line 5, in <module>
    from ..v11 import oneformer
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\__init__.py", line 4, in <module>
    from .api import make_detectron2_model, semantic_run
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\api.py", line 6, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.v11.oneformer.detectron2.config import get_cfg
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\detectron2\config\__init__.py", line 2, in <module>
    from .compat import downgrade_config, upgrade_config
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\detectron2\config\compat.py", line 27, in <module>
    from .config import CfgNode as CN
  File "<mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v11\oneformer\detectron2\config\config.py", line 7, in <module>
    from fvcore.common.config import CfgNode as _CfgNode
  File "<mypath>\comfyui\python_embeded\lib\site-packages\fvcore\common\config.py", line 8, in <module>
    from iopath.common.file_io import g_pathmgr
  File "<mypath>\comfyui\python_embeded\lib\site-packages\iopath\__init__.py", line 3, in <module>
    from iopath.common import file_lock, get_cache_dir, LazyPath, PathManager
  File "<mypath>\comfyui\python_embeded\lib\site-packages\iopath\common\__init__.py", line 3, in <module>
    from iopath.common.file_io import file_lock, get_cache_dir, LazyPath, PathManager
  File "<mypath>\comfyui\python_embeded\lib\site-packages\iopath\common\file_io.py", line 32, in <module>
    import portalocker  # type: ignore
  File "<mypath>\comfyui\python_embeded\lib\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "<mypath>\comfyui\python_embeded\lib\site-packages\portalocker\portalocker.py", line 16, in <module>
    import pywintypes
ModuleNotFoundError: No module named 'pywintypes'

Cannot import <mypath>\comfyui\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: No module named 'pywintypes'`

**Comment by api-haus** [comment]
Just rerun `install.bat`. If that doesn't help, you can try this.

`D:\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install pypiwin32`
